services:
  web:
    container_name: web
    build: 
      context: ./web
      dockerfile: Dockerfile.dev
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
    env_file:
      - .env.dev
    command: >
      sh -c "yarn install && yarn dev"
    depends_on: 
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo:5.0
    ports:
      - "57017:27017"
    volumes:
      - ./data:/data/db

volumes:
  data: