services:
  web:
    container_name: web
    build: 
      context: ./web
      dockerfile: Dockerfile.prod
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
    depends_on:
      - mongodb
    env_file:
      - .env.prod
    command: yarn start

  mongodb:
    container_name: mongodb
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

volumes:
  data: