# Use Node.js as the base image
FROM node:lts-alpine

# Set the working directory
WORKDIR /app

# Expose the port for Next.js
EXPOSE 3000

# Run the application in development mode
RUN apk update \
    && apk upgrade \
    && apk add --no-cache --upgrade bash npm
