# Use Node.js as the base image
FROM node:lts-alpine

# Set the working directory
WORKDIR /app

# Copy package.json yarn.lock, and install dependencies
COPY package.json yarn.lock ./
RUN yarn install

# Copy the entire application code
COPY . .

# Expose the port for Next.js
EXPOSE 3000

# Run the application in development mode
CMD ["yarn", "dev"]
